---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dbaas-redhat-com-v1alpha2-rdsinventory
  failurePolicy: Fail
  name: vrdsinventory.kb.io
  rules:
  - apiGroups:
    - dbaas.redhat.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    resources:
    - rdsinventories
  sideEffects: None
