name: Scan Golang project
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main
      - crda-test

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04" ]
        # Test once with explicit manifest_file, and once without
        manifest_file: [ "go.mod" ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    name: Analyse Golang project
    steps:

      - name: Checkout action
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18.7'

      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: "latest"

      - name: CRDA Scan
        id: crda_scan
        uses: redhat-actions/crda@v1
        with:
          crda_key: ${{ secrets.CRDA_KEY }}
          snyk_token: ${{ secrets.SNYK_TOKEN }}

      - name: Print Report Link
        run: echo ${{ steps.crda_scan.outputs.report_link }}